# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '0.0.1.post1.dev0+g2118572.d20211123'
version_tuple = (0, 0, 1, 'dev0', 'g2118572.d20211123')
